# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Restaurants'),
        ),
    ]
